workflows:
  android-workflow:
    name: Build APK Masaniello
    max_build_duration: 60

    environment:
      java: 17

    scripts:
      - chmod +x ./gradlew
      - ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
