workflows:
  android-workflow:
    name: Build APK Masaniello
    max_build_duration: 60
    scripts:
      - ./gradlew clean
      - ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release-unsigned.apk
