workflows:
  android-workflow:
    name: Build APK Masaniello
    max_build_duration: 60
    scripts:
      - chmod +x ./gradlew
      - ./gradlew clean
      - ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk   # prende tutto ciò che è APK nella cartella release
